Objetivo 5
Parka015/serie-motion pull request #21
Opened 2021-12-22 01:22 UTC by Parka015

En este Pull Request se han trabajado en los siguientes contenidos:

* Elección de un contenedor base.
* Creación de una imagen para pasar los tests por medio de un Dockerfile.
* Creación de un usuario sin privilegios para ejecutar el contenedor para seguir buenas prácticas.
* Instalación de lo estrictamente necesario en la imagen para que el contenedor pueda pasar los tests.
* Documentación sobre la elección del contenedor base, los criterios de búsqueda de este, la elección final tomada, como he desarrollado la imagen para la aplicación y como ejecutarla.
* Sincronización del README de DockerHub con el de Github para reflejar el estado del proyecto.
* Automatización de la construcción del contenedor cuando se actualice el repositorio en GitHub.

Se resolvieron las tareas: #19 #20  

* [x]  ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [x]  ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests?
* [x]  ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [x]  ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [x]  ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?

2021-12-22 02:25 UTC, JJ commented
⛹ Revisores → @Balrrach @amerigal @Olasergiolas

2021-12-22 07:51 UTC, Parka015 commented
@JJ Listo para corregir

2021-12-22 08:00 UTC, Parka015 commented
Hay que mencionar que los commits no son de hace 10 dias como dice Github, ni tampoco he cambiado nada de ejercicios anteriores pero por alguna razón me ha metido todos esos cambios en el pull requests. Realmente este pull request se ha trabajado desde el commit 8d30a08 en adelante

2021-12-22 13:07 UTC, JJ requested changes
Son más bien errores de detalle, pero te agradecería que lo llevaras a cabo.

2021-12-22 13:07 UTC, JJ commented on source/KNN.py
> +class KNN:
:clap:

2021-12-22 14:04 UTC, Parka015 commented on .github/workflows/Actualizar_readme_DockerHub.yml
> +name: Actualizar Readme en Dockerhub
No, en principio había pensado que si añades más información al Readme o cambias algo, sea independiente de que la imagen no se modifique. Porque sino, no podría garantizar que siempre se encuentren sincronizados

2021-12-22 14:19 UTC, Parka015 commented on Dockerfile
> +RUN pip3 install poetry &&\
Se ejecuta en /app/test aunque los archivos pyproject.toml y poetry.lock se encuentran en el raiz, por eso poetry encuentra los archivos, aunque al hacer docker run -v <directorio_raiz_proyecto>:/app/test le pase todo el contenido del proyecto, necesito tener antes pyproject.toml y poetry.lock para poder instalar las dependencias.

2021-12-22 14:28 UTC, Parka015 commented on docs/README.md
> +* Deberá contener una versión de python superior o igual a la 3.6.
Si lo he comprobado, si la memoria no me falla no he visto que ninguna tenga ni poetry, ni pytest ni invoke instalado

2021-12-22 14:31 UTC, Parka015 commented on docs/README.md
> +  * **Python** (info oficial imagen -> [aqui](https://hub.docker.com/_/python)): Con esta imagen nos garantizamos que python esta instalado, pero ahora habrá que mirar cual de todas las versiones es
Ha sido porque en principio si traen el resto de herramientas (invoke, pytest o poetry) ganarían puntos a favor, pero visto que ninguna imagen la tenia, y una de las imagenes (la de python) ya tenia python... Por eso aun asi he decidido echarle un vistazo a esas imagenes.

2021-12-22 15:09 UTC, Parka015 commented on Dockerfile
> +WORKDIR /app/test
Ambos

2021-12-22 15:51 UTC, Parka015 commented
@JJ Listo para revisión. He retocado los workflows para no usar ramas, además de que se han simplificado bastante. He retocado la documentación argumentar el porque escogí Ubuntu y Alpine además de la imagen de Python. Y corregido la orden que no hacía nada en el Dockerfile

2021-12-22 17:28 UTC, JJ requested changes
OK, error mío porque no habías puesto listo para revisión. En general trata de entender que cuando hago un comentario no es una petición de explicación adicional (en general) sino un error que convendría que modificaras para superar el objetivo.

2021-12-22 17:28 UTC, JJ commented on .github/workflows/Actualizar_readme_DockerHub.yml
> +      - 'README-md'
typo

2021-12-22 17:28 UTC, JJ commented on Dockerfile
> +WORKDIR /app/test
¿Has leído lo que pongo arriba que nada que se instale en ese directorio va a estar visible cuando montes el directorio?

2021-12-22 17:28 UTC, JJ commented on Dockerfile
> +RUN pip3 install poetry &&\
Los puedes tener en cualquier directorio. Sólo necesitas establecer el workdir para ejecutar la orden de test.

2021-12-22 17:28 UTC, JJ commented on docs/README.md
> +* Deberá contener una versión de python superior o igual a la 3.6.
Pero Python sí podría tenerla (de hecho, la 20.04 no lo tiene, lo he  comprobado. Debian no lo sé, es posible.)

2021-12-22 17:28 UTC, JJ commented on docs/README.md
> +  * **Python** (info oficial imagen -> [aqui](https://hub.docker.com/_/python)): Con esta imagen nos garantizamos que python esta instalado, pero ahora habrá que mirar cual de todas las versiones es
Insisto, la comparación tiene que ser entre imágenes iguales. La imagen Alpine es tan oficial como la Python, y puedes instalar Python como te dé la gana.

2021-12-22 17:44 UTC, Parka015 commented on .github/workflows/Actualizar_readme_DockerHub.yml
> +      - 'README-md'
A que te refieres con 'typo'?

2021-12-22 18:11 UTC, JJ commented on .github/workflows/Actualizar_readme_DockerHub.yml
> +      - 'README-md'
Error de tecleo u ortográfico.

2021-12-22 23:57 UTC, Balrrach commented on docs/README.md
> +* A ser posible se preferiría un SO tipo open-source como Linux.
BSD? :no_mouth:

2021-12-23 12:30 UTC, JJ commented on docs/README.md
> +* A ser posible se preferiría un SO tipo open-source como Linux.
No, usan un kernel diferente. Recuerda que los contenedores usan una serie de funciones específicas del kernel para aislamiento. Si los hay, son contenedores específicos para BSD

2021-12-23 12:30 UTC, JJ commented on docs/README.md
> +* A ser posible se preferiría un SO tipo open-source como Linux.
Ahora que lo pienso, está también Windows, que no es OS. Pero vas a tener que usar de todas formas. Así que borro.

2021-12-23 14:45 UTC, Parka015 commented on .github/workflows/Actualizar_readme_DockerHub.yml
> +      - 'README-md'
Ups, ya lo he visto

2022-01-08 18:41 UTC, JJ commented
¿No haces las correcciones?

2022-01-08 21:55 UTC, Parka015 commented
> ¿No haces las correcciones?

@JJ  tengo 4 asignaturas que han decidido mandar prácticas por navidad además de los exámenes, no estoy pasando muy buenos dias la verdad. Voy a tener un par de dias para sacar esto y el objetivo 6. No pienses que es que estoy pasando del tema

2022-01-08 21:56 UTC, Parka015 commented
> ¿No haces las correcciones?

@JJ  tengo 4 asignaturas que han decidido mandar prácticas por navidad además de los exámenes, no estoy teniendo descanso ninguno. Voy a tener un par de días para sacar esto y el objetivo 6. No pienses que es que estoy pasando del tema

2022-01-11 20:04 UTC, Parka015 commented
@JJ Listo para corregir

2022-01-12 13:36 UTC, JJ commented
Tienes un error en Circle y además conflictos. ¿De veras quieres que lo revise?

2022-01-12 13:44 UTC, Parka015 commented
> Tienes un error en Circle y además conflictos. ¿De veras quieres que lo revise?

Si, lo de cricleCI es porque al asociar el repositorio con CircleCI cualquier pusheo a cualquier rama, CircleCI intenta ejecutar el config.yml, el cual es del siguiente objetivo, y da el error de que no encuentra dicho archivo.

Y los conflictos es porque en la rama main cometí un error de modificar el readme hace tiempo, y por eso estan en conflicto, pero no es nada serio. Había decidido esperarme a solucionarlo cuando lo mergee

2022-01-15 20:04 UTC, Parka015 commented
@JJ puede ser que se te haya pasado echarle un vistazo al objetivo

2022-01-15 20:08 UTC, JJ commented
No, estoy esperando a que pase los tests (o los elimines de este objetivo). Si no pasan los tests, no se puede revisar.

2022-01-15 20:40 UTC, Parka015 commented
> No, estoy esperando a que pase los tests (o los elimines de este objetivo). Si no pasan los tests, no se puede revisar.

Solucionado

2022-01-19 17:18 UTC, JJ approved these changes
No se ha hecho una búsqueda demasiado extensiva de contenedores base, pero al menos se han buscado criterios razonables.

2022-02-06 21:35 UTC, merged